App:
  WorkingDirectory: var/
  MaxUsers: 512
  AllowRegistration: true
  MaxNickLen: 15
  MenuMaxIdleTime: 600
  PostLoginCommands:
    - mkdir %w/userdata/%u
    - mkdir %w/userdata/%u/dumplog
    - mkdir %w/userdata/%u/ttyrec

Menus:
  anonymous:
    Banner: 'Shell Game Launcher - Anonymous access%n======================================'
    XOffset: 5
    YOffset: 2
    MenuEntries:
      - Key: l
        Label: login
        Action: login
      - Key: r
        Label: register
        Action: register
      - Key: w
        Label: watch
        Action: watch_menu
      - Key: q
        Label: quit
        Action: quit
  logged_in:
    Banner: 'Shell Game Launcher%n==================='
    XOffset: 5
    YOffset: 2
    MenuEntries:
      - Key: p
        Label: play Nethack 3.7
        Action: play nethack3.7
      - Key: o
        Label: edit game options
        Action: menu options
      - Key: w
        Label: watch
        Action: watch
      - Key: r
        Label: replay
        Action: replay
      - Key: c
        Label: change password
        Action: passwd
      - Key: m
        Label: change email
        Action: chmail
      - Key: q
        Label: quit
        Action: quit
  test:
    Banner: 'Shell Game Launcher%n==================='
    XOffset: -1
